name: CD Pipeline

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  build:
    name: Build Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
  deploy:
    name: Deploy Runner
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Image Version
        run: |
          echo IMAGE_VERSION=$(echo ${{ github.ref_name }} | sed "s/^release\///") >> $GITHUB_ENV
          echo "Image Version - $IMAGE_VERSION"
      - name: Push Image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.IMAGE_VERSION }}
          tags: ${{ vars.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_VERSION }}
