name: CI Pipeline

on:
  push:
    branches:
      - 'feature/**'
      - 'develop'
      - 'bugfix/**'
      - 'release/**'
      - 'main'
      - 'hotfix/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Run Build
        run: npm run build
